#!/bin/bash
nl=$'\n'
string=$"Help:
${nl}Functions:
${nl}1. Calculator. Insert \"calc\". Then insert \"sum\"/\"sub\"/\"mul\"/\"div\" and two integer numbers. The programm will summ, substract, multiply or divide the numbers.
${nl}2. Search. Insert \"search\". Then insert path to the directory and a regular expression. The programm will search in the files in the directory in accordance with the expression.
${nl}3. Reversed wrtiter. Insert \"reverse\". Then insert names of two files. The programm will write reversed content of the first file into the second file.
${nl}4. String length. Insert \"strlen\". Then insert a string. The programm will return length of the string.
${nl}5. Log. Insert \"log\". The programm will return warnings and informational messages from the file /var/log/anaconda/X.log.
${nl}6. Exits. Insert \"exit\". The progamm ends its work with the exit status inserted in the third arguement.
${nl}7. Help. Insert \"help\". The progamm shows help manual (you're looking at it right now).
${nl}8. Interactive mode. Insert \"inreactive\". The programm will go into the ineractive mode and show you the menu."
echo "$string"

