#!/bin/bash
nl=$'\n'
menu=$"Menu:
${nl}a. Calculator;
${nl}b. Search;
${nl}c. Reverse;
${nl}d. String Length;
${nl}e. Log;
${nl}f. Exit;
${nl}g. Help;
${nl} Insert the letter or the name of the command. To exit insert Exit or f."

./FileCheck
calcFlag=0;
searchFlag=0;
reverseFlag=0;
strlenFlag=0;
logFlag=0;
helpFlag=0;
directoryPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
fileName=calc
fileExist=$(find $directoryPath -name $fileName)
if [[ $fileExist ]]
then
calcFlag=1
fi
fileName=search
fileExist=$(find $directoryPath -name $fileName)
if [[ $fileExist ]]
then
searchFlag=1
fi
fileName=reverse
fileExist=$(find $directoryPath -name $fileName)
if [[ $fileExist ]]
then
reverseFlag=1
fi
fileName=strlen
fileExist=$(find $directoryPath -name $fileName)
if [[ $fileExist ]]
then
strlenFlag=1
fi
fileName=log
fileExist=$(find $direcotoryPath -name $fileName)
if [[ $fileExist ]]
then
logFlag=1
fi
fileName=help
fileExist=$(find $directoryPath -name $fileName)
if [[ $fileExist ]]
then
helpFlag=1
fi

while :
do
echo "$menu"
read insert
if [[ "$insert" = "a" ]] || [[ "$insert" = "Calculator" ]]
then
if [[ $calcFlag -eq 0 ]]
then 
echo "The file is still missing."
continue
else
echo "Insert a command and two integer numbers."
read command number1 number2
./calc $command $number1 $number2
fi
else
if [[ "$insert" = "f" ]] || [[ "$insert" = "Exit" ]]
then
echo "Insert two or more integer numeric arguements or don't."
read arg1 arg2
exit $arg2
else
if [[ "$insert" = "b" ]] || [[ "$insert" = "Search" ]]
then
if [[ $searchFlag -eq 0 ]]
then
echo "The file is still missing." 1>&2
continue
else
echo "Insert the name of the directory and a regular expression."
read dir expr
./search $dir $expr
fi
else
if [[ "$insert" = "c" ]] || [[ "$insert" = "reverse" ]]
then
if [[ $reverseFlag -eq 0 ]]
then
echo "The file is still missing." 1>&2
continue
else
echo "Insert two names of the files."
read file1 file2
./reverse $file1 $file2
fi
else
if [[ "$insert" = "d" ]] || [[ "$insert" = "String Length" ]]
then
if [[ $strlenFlag -eq 0 ]]
then
echo "The file is still missing." 1>&2
continue
else
echo "Insert a line."
read line
./strlen $line
fi
else
if [[ "$insert" = "e" ]] || [[ "$insert" = "Log" ]]
then
if [[ $logFlag -eq 0 ]]
then
echo "The file is still missing." 1>&2
continue
else
./log
fi
else
if [[ "$insert" = "g" ]] || [[ "$insert" = "Help" ]]
then
if [[ $helpFlag -eq 0 ]]
then
echo "The file is still missing." 1>&2
continue
else
./help
fi 
else
echo "There's no such command, look the menu up." 1>&2
fi
fi
fi
fi
fi
fi
fi
done 
