#!/bin/bash
Yellow='\033[1;33m'
Blue='\033[1;34m'
NC='\033[0m'
echo -e "${Yellow}Warnings:${NC}"
grep -r "EE" /var/log/anaconda/X.log | sed 's/EE/${Yellow}Warning${NC}/'
echo -e "${Blue}Information:${NC}"
grep -r "II" /var/log/anaconda/X.log | sed 's/II/${Blue}Information${NC}/'

