#!/bin/bash
Yellow='\e[1;33m'
Blue='\e[1;34m'
NC='\e[0m'
Info="${Blue}Information${NC}"
echo -e "${Yellow}Warnings:${NC}"
grep -e "EE" /var/log/anaconda/X.log | sed ''/WW/s//`printf "\033[33mWarning:\033[0m"`/''
echo -e "${Blue}Information:${NC}"
grep -e "II" /var/log/anaconda/X.log | sed ''/II/s//`printf "\033[34mInformation:\033[0m"`/''
